owners = ["rtyler"]
nickname = "bibbybot"
alt_nicks = ["bibby_", "bibbybot__"]
username = "bibby"
realname = "Bibby"
server = "irc.libera.chat"
port = 6697
use_tls = true
cert_path = "libera.der"
channels = ["#bibby"]


[options]
# !fact add <foo>, !fact delete <foo>, !fact help
command_fact = "http://localhost:8042"
command_what = "http://localhost:8042"

command_fallback = "http://localhost:8041"
